"""make_google_doc_fields_nullable

Revision ID: 07e13d1b6445
Revises: ba6e853ec41a
Create Date: 2025-11-26 13:00:05.569819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e13d1b6445'
down_revision: Union[str, Sequence[str], None] = 'ba6e853ec41a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deep_dives', 'google_doc_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('deep_dives', 'google_doc_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deep_dives', 'google_doc_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('deep_dives', 'google_doc_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
