"""Initial schema

Revision ID: ba6e853ec41a
Revises: 
Create Date: 2025-11-26 03:15:29.052681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba6e853ec41a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgcrypto extension for gen_random_uuid()
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_batches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recipient_emails', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('subject_line', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='email_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filter_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rule_type', sa.Enum('MUST_HAVE', 'MUST_AVOID', 'GOOD_TOPIC', 'BORDERLINE', name='rule_type'), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('ORIGINAL', 'LEARNED', 'MANUAL', name='rule_source'), nullable=False),
    sa.Column('learned_from_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_filter_rules_is_active', 'filter_rules', ['is_active'], unique=False)
    op.create_index('ix_filter_rules_priority', 'filter_rules', ['priority'], unique=False)
    op.create_table('refinement_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('total_articles_reviewed', sa.Integer(), nullable=False),
    sa.Column('total_good', sa.Integer(), nullable=False),
    sa.Column('total_no', sa.Integer(), nullable=False),
    sa.Column('total_why_not', sa.Integer(), nullable=False),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accepted_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refinement_logs_week_start', 'refinement_logs', ['week_start'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('RSS', 'SEARCH_QUERY', 'MANUAL', name='source_type'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('search_query', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('total_surfaced', sa.Integer(), nullable=False),
    sa.Column('total_approved', sa.Integer(), nullable=False),
    sa.Column('total_rejected', sa.Integer(), nullable=False),
    sa.Column('last_fetched', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_sources_is_active', 'sources', ['is_active'], unique=False)
    op.create_index('ix_sources_trust_score', 'sources', ['trust_score'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('external_url', sa.String(length=500), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('amish_angle', sa.Text(), nullable=False),
    sa.Column('filter_score', sa.Float(), nullable=False),
    sa.Column('filter_notes', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('emailed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'EMAILED', 'GOOD', 'REJECTED', 'PASSED', name='article_status'), nullable=False),
    sa.Column('google_doc_id', sa.String(length=100), nullable=True),
    sa.Column('google_doc_url', sa.String(length=500), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('email_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_batch_id'], ['email_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_url')
    )
    op.create_index('ix_articles_daily_email', 'articles', ['status', 'filter_score', 'discovered_date'], unique=False, postgresql_using='btree')
    op.create_index('ix_articles_discovered_date', 'articles', ['discovered_date'], unique=False)
    op.create_index('ix_articles_source_id', 'articles', ['source_id'], unique=False)
    op.create_index('ix_articles_status', 'articles', ['status'], unique=False)
    op.create_table('deep_dives',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('headline_suggestion', sa.String(length=500), nullable=False),
    sa.Column('key_points', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('additional_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('full_report_text', sa.Text(), nullable=False),
    sa.Column('google_doc_id', sa.String(length=100), nullable=False),
    sa.Column('google_doc_url', sa.String(length=500), nullable=False),
    sa.Column('google_sheet_row', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_index('ix_deep_dives_article_id', 'deep_dives', ['article_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Enum('GOOD', 'NO', 'WHY_NOT', name='feedback_rating'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_index('ix_feedback_article_id', 'feedback', ['article_id'], unique=False)
    op.create_index('ix_feedback_clicked_at', 'feedback', ['clicked_at'], unique=False)
    op.create_index('ix_feedback_rating', 'feedback', ['rating'], unique=False)
    # ### end Alembic commands ###
    
    # Add CHECK constraint on filter_score (must be between 0.0 and 1.0)
    op.create_check_constraint(
        'ck_articles_filter_score_range',
        'articles',
        'filter_score >= 0.0 AND filter_score <= 1.0'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Drop CHECK constraint
    op.drop_constraint('ck_articles_filter_score_range', 'articles', type_='check')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_rating', table_name='feedback')
    op.drop_index('ix_feedback_clicked_at', table_name='feedback')
    op.drop_index('ix_feedback_article_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_deep_dives_article_id', table_name='deep_dives')
    op.drop_table('deep_dives')
    op.drop_index('ix_articles_status', table_name='articles')
    op.drop_index('ix_articles_source_id', table_name='articles')
    op.drop_index('ix_articles_discovered_date', table_name='articles')
    op.drop_index('ix_articles_daily_email', table_name='articles', postgresql_using='btree')
    op.drop_table('articles')
    op.drop_index('ix_sources_trust_score', table_name='sources')
    op.drop_index('ix_sources_is_active', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_refinement_logs_week_start', table_name='refinement_logs')
    op.drop_table('refinement_logs')
    op.drop_index('ix_filter_rules_priority', table_name='filter_rules')
    op.drop_index('ix_filter_rules_is_active', table_name='filter_rules')
    op.drop_table('filter_rules')
    op.drop_table('email_batches')
    # ### end Alembic commands ###
